# Output and Production {#production}

```{r, include = FALSE}
library(readr)
library(quantmod)
library(zoo)
library(tidyquant)
library(tidyverse)
library(lubridate)
library(reshape2)
library(dplyr)
library(wbstats)
library(ggplot2)
library(usmap)
library(gtrendsR)
library(tmap)
library(spData)
library(pwt9)
library(googleVis)


```

Measures of output and production

```{r output, echo = FALSE, fig.cap='Output Exhibits Both Growth and Cycles', out.width='80%', fig.asp=.75, fig.align='center'}

recessions.df = read.table(textConnection(
  "Peak, Trough
  1948-11-01, 1949-10-01
  1953-07-01, 1954-05-01
  1957-08-01, 1958-04-01
  1960-04-01, 1961-02-01
  1969-12-01, 1970-11-01
  1973-11-01, 1975-03-01
  1980-01-01, 1980-07-01
  1981-07-01, 1982-11-01
  1990-07-01, 1991-03-01
  2001-03-01, 2001-11-01
  2007-12-01, 2009-06-01
  2020-02-01, 2020-06-01"), sep=',',
  colClasses=c('Date', 'Date'), header=TRUE)

startdate <- round_date(Sys.Date() - lubridate::years(25),"month")
enddate <- round_date(Sys.Date())

df <- tq_get("GDPC1", 
                 get = "economic.data",
                 from = startdate)

df %>% 
  spread(symbol,price) %>%
  mutate(GDP = GDPC1) %>%
  mutate(date = date + months(3)) -> df

df %>% ggplot(aes(x=date,y=GDP,label=GDP)) + 
  geom_rect(data=recessions.df, inherit.aes=F, aes(xmin=Peak,
    xmax=Trough, ymin=-Inf, ymax=+Inf), fill='darkgray', alpha=0.5) +
  geom_line(size=1.05) +
    theme_light() +
    theme(legend.position="none",
        plot.caption=element_text(hjust=0),
        plot.title=element_text(size=16,color="black"))+
  labs(x = "", y = "", color = "Series", 
       title="U.S. Gross Domestic Product: Quarterly",
       subtitle="Billions of Chained 2012 Dollars (SA)",
       caption="Source: U.S. Bureau of Economic Analysis [GDPC1]"
) + 
    scale_y_continuous(labels=scales::comma,sec.axis=dup_axis())+
    coord_cartesian(xlim=c(startdate,enddate),ylim=c(floor(min(df$GDP)),ceiling(max(df$GDP))))
```



```{r output2, echo = FALSE, fig.cap='Output Exhibits Both Growth and Cycles', out.width='80%', fig.asp=.75, fig.align='center'}

df <- tq_get("GDPC1", 
                 get = "economic.data",
                 from = startdate - lubridate::years(1))

df %>% 
  spread(symbol,price) %>%
  mutate(pct_chg = (GDPC1/lag(GDPC1,4) - 1) * 100) %>%
  mutate(date = date + months(3)) %>%
  filter(complete.cases(.)) -> df

df %>% ggplot(aes(x=date,y=pct_chg,label=pct_chg)) + 
  geom_rect(data=recessions.df, inherit.aes=F, aes(xmin=Peak,
    xmax=Trough, ymin=-Inf, ymax=+Inf), fill='darkgray', alpha=0.5) +
  geom_line(size=1.05) +
    theme_light() +
    theme(legend.position="none",
        plot.caption=element_text(hjust=0),
        plot.title=element_text(size=16,color="black"))+
  labs(x = "", y = "", color = "Series", 
       title="Growth Rate of U.S. Gross Domestic Product",
       subtitle="Year over year percentage change",
       caption="Source: U.S. Bureau of Economic Analysis [GDPC1]"
) + 
    scale_y_continuous(labels=scales::comma,sec.axis=dup_axis())+
    coord_cartesian(xlim=c(startdate - lubridate::years(1),enddate),ylim=c(floor(min(df$pct_chg)),ceiling(max(df$pct_chg))))
```


```{r output3, echo = FALSE, fig.cap='Per Capita GDP Might be More Important', out.width='80%', fig.asp=.75, fig.align='center'}

df <- tq_get("A939RX0Q048SBEA", 
                 get = "economic.data",
                 from = startdate)

df %>% 
  spread(symbol,price) %>%
  mutate(GDP = A939RX0Q048SBEA) %>%
  mutate(date = date + months(3)) -> df

df %>% ggplot(aes(x=date,y=GDP,label=GDP)) + 
  geom_rect(data=recessions.df, inherit.aes=F, aes(xmin=Peak,
    xmax=Trough, ymin=-Inf, ymax=+Inf), fill='darkgray', alpha=0.5) +
  geom_line(size=1.05) +
    theme_light() +
    theme(legend.position="none",
        plot.caption=element_text(hjust=0),
        plot.title=element_text(size=16,color="black"))+
  labs(x = "", y = "", color = "Series", 
       title="Per Capita U.S. Gross Domestic Product: Quarterly",
       subtitle="Billions of Chained 2012 Dollars (SA)",
       caption="Source: U.S. Bureau of Economic Analysis [A939RX0Q048SBEA]"
) + 
    scale_y_continuous(labels=scales::comma,sec.axis=dup_axis())+
    coord_cartesian(xlim=c(startdate,enddate),ylim=c(floor(min(df$GDP)),ceiling(max(df$GDP))))
```

```{r output4, echo = FALSE, fig.cap='Per Capita Also Exhibits Cycles', out.width='80%', fig.asp=.75, fig.align='center'}

df <- tq_get("A939RX0Q048SBEA", 
                 get = "economic.data",
                 from = startdate - lubridate::years(1))

df %>% 
  spread(symbol,price) %>%
  mutate(pct_chg = (A939RX0Q048SBEA/lag(A939RX0Q048SBEA,4) - 1) * 100) %>%
  mutate(date = date + months(3)) %>%
  filter(complete.cases(.)) -> df

df %>% ggplot(aes(x=date,y=pct_chg,label=pct_chg)) + 
  geom_rect(data=recessions.df, inherit.aes=F, aes(xmin=Peak,
    xmax=Trough, ymin=-Inf, ymax=+Inf), fill='darkgray', alpha=0.5) +
  geom_line(size=1.05) +
    theme_light() +
    theme(legend.position="none",
        plot.caption=element_text(hjust=0),
        plot.title=element_text(size=16,color="black"))+
  labs(x = "", y = "", color = "Series", 
       title="Growth Rate of Per Capita U.S. Gross Domestic Product",
       subtitle="Year over year percentage change",
       caption="Source: U.S. Bureau of Economic Analysis [A939RX0Q048SBEA]"
) + 
    scale_y_continuous(labels=scales::comma,sec.axis=dup_axis())+
    coord_cartesian(xlim=c(startdate - lubridate::years(1),enddate),ylim=c(floor(min(df$pct_chg)),ceiling(max(df$pct_chg))))
```

```{r output5, echo = FALSE, fig.cap='Per Capita Also Exhibits Cycles', out.width='80%', fig.asp=.75, fig.align='center'}

startdate <- round_date(Sys.Date() - lubridate::years(70),"month")
enddate <- round_date(Sys.Date() + lubridate::years(5))

df <- tq_get(c("GDPC1","GDPPOT"), 
             get = "economic.data",
             from = startdate,
             to = enddate)

df %>% 
  spread(symbol,price) %>%
  rename(GDP = GDPC1) %>%
  mutate(date = date + months(3)) -> df


df %>%
  mutate(post08 = ifelse((date < "2009-06-01"),0,1)) %>%
  mutate(pct_chg = ((GDPPOT/lag(GDPPOT,1))-1)) %>%
  group_by(post08) %>%
  mutate(avggrowth = mean(pct_chg, na.rm=TRUE),
         rollgrowth = rollmean(pct_chg, 48, na.pad = TRUE, align = "right"),
         Count = 1:n(),
         endval = last(GDPPOT),
         min1 = min(rollgrowth, na.rm=TRUE)) %>% 
  transform(endval = min(endval),
            mingrowth = max(min1),
            avggrowth = max(avggrowth)) %>% 
  mutate(newpost08 = ifelse(post08 == 1,endval*(1+avggrowth)^Count,GDPPOT),
         minpost08 = ifelse(post08 == 1,endval*(1+mingrowth)^Count,GDPPOT)) -> df2


ggplot(data=filter(df2,!is.na(GDPPOT)), aes(x=date,y=GDP,label=GDP)) + 
  geom_line(linetype=2,aes(y=GDPPOT))+
  geom_line(aes(y=newpost08), linetype=2, color = "red")+
  geom_line(aes(y=minpost08), linetype=2, color = "green")+
  geom_rect(data=recessions.df, inherit.aes=F, aes(xmin=Peak,
                                                   xmax=Trough, ymin=-Inf, ymax=+Inf), fill='darkgray', alpha=0.5) +
  geom_line(size=1.1, na.rm=TRUE) +
  theme_light(base_size=8) +
  theme(legend.position="top",
        plot.caption=element_text(hjust=0),
        plot.title=element_text(size=16,color="black"))+
  labs(x = "", y = "", color = "Series", 
       title="U.S. Gross Domestic Product: Quarterly and \nAlternative Potential Scenarios",
       subtitle="Black line, billions of chained 2012 dollars (SA), dashed shows potential GDP \nRed line, GDP potential if growth at pre-2008 average \nGreen line, GDP potential if growth at worst 12-year average",
       caption="Source: U.S. Bureau of Economic Analysis [GDPC1], Congressional Budget Office [GDPPOT]/n
       Note: Growth rates calculated as average one period percentage change."
  ) + 
  scale_y_continuous(labels=scales::comma,sec.axis=dup_axis())+
  coord_cartesian(xlim=c(startdate,enddate),ylim=c(floor(min(df$GDP)),ceiling(max(df$GDP))))


```

```{r output6, echo = FALSE, fig.cap='Per Capita Also Exhibits Cycles', out.width='80%', fig.asp=.75, fig.align='center'}

df %>% 
  mutate(gdpgrowth = (((GDP/lag(GDP,1))^4-1)*100),
         potgrowth = (((GDPPOT/lag(GDPPOT,1))^4-1)*100)) -> df3

startdate = as.Date("1990-01-01")
range = c(floor(min(df3$gdpgrowth,na.rm=TRUE)),ceiling(max(df3$gdpgrowth,na.rm=TRUE)))

ggplot(data=filter(df3,!is.na(potgrowth) & date > startdate), aes(x=date,y=gdpgrowth,label=gdpgrowth)) + 
  geom_line(linetype=1,size=1.1,color="red",aes(y=potgrowth))+
  geom_rect(data=recessions.df, inherit.aes=F, aes(xmin=Peak,
                                                   xmax=Trough, ymin=-Inf, ymax=+Inf), fill='darkgray', alpha=0.5) +
  geom_line(size=1.1, na.rm=TRUE) +
  theme_light(base_size=8) +
  theme(legend.position="top",
        plot.caption=element_text(hjust=0),
        plot.title=element_text(size=16,color="black"))+
  labs(x = "", y = "", color = "Series", 
       title="U.S. Gross Domestic Product: Quarterly Growth",
       subtitle="Black line, annualized growth rate (SA), Red line, annualized growth rate of potential GDP",
       caption="Source: U.S. Bureau of Economic Analysis [GDPC1], Congressional Budget Office [GDPPOT]"
  ) + 
  scale_y_continuous(labels=scales::comma,sec.axis=dup_axis())+
  coord_cartesian(xlim=c(startdate,enddate),ylim=range)

```



